### ISSUE TITLE
Can support MySql?

### ISSUE THREAD

**Issue by ghost** [jsakamoto/EntityFrameworkCore.IndexAttribute#11]
thanks

**Comment by jsakamoto** [comment]
I'm sorry to I'm not familiar with MySql, but anyway, did you try this package on a MySql?

If you did it, could you tell me what happened at that time?

In my guessing, it will be worked fine because this package is just based on a standard feature of the EntityFramework Core. 

There are no tricks.
The doing of this package is equal to the calling the model-creating fluent API of the Entity Framework Core.

**Comment by ghost** [comment]
Toolbelt.ComponentModel.DataAnnotations.Schema.V5.IndexColumn
can support MySql

Thanks
